'use strict';
// 有限的机械映射检查；轻量 DOM 夹具不是浏览器，也不运行模拟器。
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),crypto=require('crypto');
const root=path.resolve(__dirname,'../..'),html=fs.readFileSync(path.join(root,'docs/v4-strategy-study.html'),'utf8');
const payload=JSON.parse(html.match(/<script id="studyPayload" type="application\/json">([\s\S]*?)<\/script>/)[1]);
const js=fs.readFileSync(path.join(__dirname,'page.js'),'utf8')+'\n'+fs.readFileSync(path.join(__dirname,'extension.js'),'utf8'),cases=[],consoleMessages=[];
function fixture(input){
 const els={},resizeObservers=[],timers=new Map();let timerId=0;
 class Element{
  constructor(tag,body=''){this.tag=tag;this.handlers={};this.dataset={};this.parentElement={clientWidth:600};this.clientWidth=1000;this.options=[];this._value='';this.checked=false;this.innerHTML=body;}
  set innerHTML(v){this.htmlWrites=(this.htmlWrites||0)+1;this._html=v;if(this.tag==='select'){this.options=[...v.matchAll(/<option(?: value="([^"]*)")?[^>]*>([^<]*)<\/option>/g)].map(m=>({value:m[1]||m[2],textContent:m[2]}));if(!this.options.some(o=>o.value===this._value))this._value=this.options[0]?.value||'';}for(const m of v.matchAll(/<(\w+)[^>]*\bid="([^"]+)"[^>]*>/g))if(!els[m[2]])els[m[2]]=new Element(m[1]);}
  get innerHTML(){return this._html;}get value(){return this._value;}set value(v){this._value=v;}get selectedOptions(){return this.options.filter(o=>o.value===this._value);}setAttribute(k,v){this[k]=v;}addEventListener(k,v){this.handlers[k]=v;}scrollIntoView(){}
 }
 for(const m of html.matchAll(/<(\w+)[^>]*\bid="([^"]+)"[^>]*>/g)){const start=m.index+m[0].length,end=html.indexOf('</'+m[1]+'>',start);els[m[2]]=new Element(m[1],end>=start?html.slice(start,end):'');}
 els.studyPayload.textContent=JSON.stringify(input);
 const context={document:{getElementById:id=>{assert(els[id],'missing element '+id);return els[id];},querySelectorAll:()=>[]},window:{},ResizeObserver:class{constructor(callback){this.callback=callback;}observe(target){resizeObservers.push({target,callback:this.callback});}},setTimeout:fn=>{timers.set(++timerId,fn);return timerId;},clearTimeout:id=>timers.delete(id),console:{warn:m=>consoleMessages.push('warn: '+m),error:m=>consoleMessages.push('error: '+m),log(){}},URL,Blob};
 vm.createContext(context);vm.runInContext(js,context);return {els,study:context.window.study,resizeObservers,flushTimers:()=>{const pending=[...timers.values()];timers.clear();pending.forEach(fn=>fn());}};
}
function check(name,fn){fn();cases.push(name);}
const actual=fixture(payload),{els,study}=actual;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
check('guide: all six families and every narrative field are default-visible',()=>{for(const f of payload.guide.families)for(const key of ['title','question','change','motivation','tradeoff','observed','iteration','value','frozen_label'])assert(els.strategyCards.innerHTML.includes(esc(f[key])),f.id+' '+key);for(const t of payload.guide.takeaways)assert(els.judgments.innerHTML.includes(esc(t.text)));});
check('guide: combination meanings, rationale, observations and value render',()=>{const g=payload.guide.combinations;for(const t of [g.question,g.observed,g.value,...g.design.flatMap(v=>[v.meaning,v.why])])assert(els.combinationGuide.innerHTML.includes(esc(t)));});
check('development matrix: 18 configurations and every R2/R3/R4 strategy run',()=>{assert.equal(els.developmentOverview.dataset.configurationCount,18);const ids=[...els.developmentOverview.innerHTML.matchAll(/data-score-run="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,36);for(const r of payload.data.rows.filter(r=>r.experiment_category==='strategy'&&['R2','R3','R4'].includes(r.stage_group)))assert(ids.includes(r.run_id),r.run_id);});
check('frozen matrix: 13x4 records, exact T/P candidates, negative totals retained',()=>{const ids=[...els.frozenOverview.innerHTML.matchAll(/data-score-run="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,52);assert(ids.includes('r3-t-cap900-conditional-demo'));assert(ids.includes('r3-p-p12-dev-season'));for(const r of payload.data.rows.filter(r=>r.stage_group==='R5')){assert(ids.includes(r.run_id));assert(els.frozenOverview.innerHTML.includes(r.total.toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})));}});
check('frozen matrix delta toggle preserves official totals as secondary values',()=>{els.overviewDelta.checked=true;els.overviewDelta.handlers.change();assert(els.frozenOverview.innerHTML.includes('总分'));assert.equal(els.frozenOverview.dataset.configurationCount,13);});
check('screenshots: direct decimal summaries, canonical alpha/beta/gamma/delta mapping',()=>{for(const c of payload.leaderboard_screenshots.cards){assert.equal(study.screenshotDisplay(c.name,'median'),c.summary.median_total);assert.equal(study.screenshotDisplay(c.name,'top'),c.summary.top_total);assert(els.officialMatrix.innerHTML.includes(c.summary.median_total));assert(els.officialMatrix.innerHTML.includes(c.summary.top_total));}assert(els.leaderboardScope.innerHTML.includes('样本数 8'));assert(els.leaderboardScope.innerHTML.includes('拍摄时间未知'));});
check('external: actual records map independently; missing results never use research scores',()=>{if(payload.external_results?.rows?.length){for(const r of payload.external_results.rows)assert.equal(study.officialTotal(study.localRecord(r.family,r.card)),r.score_available===false?null:r.total);}else{assert(els.externalStatus.textContent.includes('0 / 12'));for(const c of ['alpha','beta','gamma','delta'])for(const f of ['baseline','D','DTGP'])assert.equal(study.localRecord(f,c),undefined);assert.equal((els.officialMatrix.innerHTML.match(/待完成／未取得|未运行（缺完整环境）/g)||[]).length,12);}});
check('historical records: current official-platform label takes precedence; no zero bars',()=>{if(/blocked/.test(payload.external_results?.status||'')){const onlineOnly=payload.guide.external.status==='official_cards_online_only',label=onlineOnly?'未提交（仅平台评测）':'未运行（缺完整环境）';assert.equal(els.officialMatrix.innerHTML.split(label).length-1,12);assert.equal(els.officialCharts.innerHTML.split(label).length-1,4);if(onlineOnly){assert(els.externalStatus.textContent.startsWith('预定正式卡平台评测：0 / 12 已取得成绩。'));assert(!els.officialMatrix.innerHTML.includes('本地官方'));assert(!els.officialMatrix.innerHTML.includes('本地科学'));assert(!els.officialMatrix.innerHTML.includes('本地冻结'));assert(els.officialMatrix.innerHTML.includes('预定正式卡对照，尚无平台成绩'));assert(!els.officialMatrix.innerHTML.includes('缺完整环境'));assert(!els.officialCharts.innerHTML.includes('缺完整环境'));}for(const c of ['alpha','beta','gamma','delta']){const svg=els['officialChart-'+c].innerHTML;assert(svg.includes('截图中位数'));assert(svg.includes('截图最高分'));assert(!svg.includes('本地 baseline'));}}});
check('external: blocked complete environment renders exact no-run labels',()=>{const p=JSON.parse(JSON.stringify(payload));p.guide.external.status='blocked';p.external_results={status:'blocked',rows:[]};p.input_states.external.status='loaded';const a=fixture(p);assert.equal((a.els.officialMatrix.innerHTML.match(/未运行（缺完整环境）/g)||[]).length,12);assert(a.els.externalStatus.textContent.includes('固定对照未运行'));});
check('external: worker schema maps four cards and three candidates independently',()=>{const p=JSON.parse(JSON.stringify(payload));p.external_results={rows:[]};for(const [ci,card]of ['alpha','beta','gamma','delta'].entries())for(const [fi,family]of ['baseline','D','DTGP'].entries())p.external_results.rows.push({card,family,candidate:family.toLowerCase(),total:ci*100+fi+.25,score_available:true,full_season_complete:true,evidence_links:{metrics:'../runs/example/metrics.json'}});p.input_states.external.status='loaded';const a=fixture(p);assert(a.els.externalStatus.textContent.includes('12 / 12'));for(const r of p.external_results.rows)assert.equal(a.study.officialTotal(a.study.localRecord(r.family,r.card)),r.total);assert(a.els.officialMatrix.innerHTML.includes('../experiments/v4/external_evaluation/../runs/example/metrics.json'));});
check('external: unavailable score flags, zero values, download failure and absent screenshots',()=>{assert.equal(study.officialTotal({total:0,score_available:true}),0);assert.equal(study.officialTotal({total:0,score_available:false}),null);const p=JSON.parse(JSON.stringify(payload));p.guide.external.status='pending';p.external_results={cards:[{card_id:'alpha',status:'download_failed'}],rows:[]};p.leaderboard_screenshots=null;const a=fixture(p);assert(a.els.officialMatrix.innerHTML.includes('下载／获取失败'));assert.equal((a.els.officialMatrix.innerHTML.match(/截图值未知/g)||[]).length,8);});
check('version-specific explanation: R3 summaries and R5 current-card statements',()=>{study.selectRun('r3-t-cap900-conditional-dev-season');assert(els.selectedMechanism.innerHTML.includes('该家族开发过程总结'));assert(els.selectedMechanism.innerHTML.includes(esc(payload.guide.families.find(f=>f.id==='T').iteration)));study.selectRun('r3-d-power075-demo');assert(els.selectedMechanism.innerHTML.includes(esc(payload.guide.families.find(f=>f.id==='D').iteration)));study.selectRun('r5-t-holdout-stress');assert(!els.selectedMechanism.innerHTML.includes('87/123'));});
check('extension guide: six directions, combinations, holdout findings and takeaways remain default-visible',()=>{for(const f of payload.extension_guide.families)for(const key of ['title','question','change','motivation','tradeoff','observed','iteration','value','frozen_label'])if(f[key])assert(els.extensionStrategyCards.innerHTML.includes(esc(f[key])),f.id+' '+key);assert(els.extensionBaseline.innerHTML.includes(esc(payload.extension_guide.data_boundary)));for(const c of payload.extension_guide.combinations||[])for(const key of ['meaning','why','observed'])assert(els.extensionCombinationGuide.innerHTML.includes(esc(c[key])));for(const [key,target]of [['holdout','extensionHoldoutGuide'],['takeaways','extensionTakeaways']])for(const c of payload.extension_guide[key]||[])for(const field of ['title','text'])assert(els[target].innerHTML.includes(esc(c[field])));});
check('two-study isolation: original 84 preserved; extension 97 includes 78 research and 19 verification; negative scores are completed results',()=>{assert.deepEqual(payload.data,JSON.parse(fs.readFileSync(path.join(root,'experiments/v4/results/all_runs.json'),'utf8')));assert.deepEqual(payload.extension_data,JSON.parse(fs.readFileSync(path.join(root,'experiments/v4/extension/results/all_runs.json'),'utf8')));assert.equal(payload.data.rows.length,84);const oldIds=new Set(payload.data.rows.map(r=>r.run_id));assert(!payload.extension_data.rows.some(r=>oldIds.has(r.run_id)));if(payload.extension_guide.status==='completed_frozen_holdout'){assert.equal(payload.extension_data.rows.length,97);assert.equal(payload.extension_data.rows.filter(r=>r.verification_only).length,19);assert.equal(payload.extension_data.rows.filter(r=>!r.verification_only).length,78);assert.equal(payload.extension_data.rows.filter(r=>(r.declared_stage||r.stage)==='N5').length,52);}for(const r of payload.extension_data.rows.filter(r=>(r.declared_stage||r.stage)==='N5')){assert(r.full_season_complete);assert.equal(study.extension.score(r),r.total);if(r.total<0)assert(els.extensionHoldoutMatrix.innerHTML.includes('data-extension-score-run="'+r.run_id+'"'));}});
check('extension development: all N2/N3/N4 runs plus reused references; D deltas never use old baseline',()=>{const rs=payload.extension_data.rows.filter(r=>!r.verification_only&&['N2','N3','N4'].includes(r.declared_stage||r.stage));for(const r of rs){assert(els.extensionDevelopmentMatrix.innerHTML.includes('data-extension-score-run="'+r.run_id+'"'));assert.equal(study.extension.delta(r),r.delta_vs_D_available?r.delta_vs_D:null);}assert.equal(study.extension.delta({total:123,delta_vs_D:null,delta_vs_D_available:false}),null);assert.equal(study.extension.score({total:0,score_available:true}),0);assert.equal(study.extension.score({total:0,score_available:false}),null);});
check('extension frozen development: exact N2/N4 candidates and reused references; no N3 substitution',()=>{for(const spec of study.extension.frozenCases()){const d=study.extension.frozenDevelopment(spec),id=spec.development_case_id||spec.case_id,reused=['official-baseline','D-linear','DTGP-frozen02'].includes(id),stage=reused?'复用参照':id.split('+').length>2?'N4':'N2',pool=reused?payload.extension_data.reference_rows:payload.extension_data.rows.filter(r=>(r.declared_stage||r.stage)===stage&&!r.verification_only),rs=['demo','dev-season'].map(card=>pool.filter(r=>r.case_id===id&&r.card===card));assert.equal(d.stage,stage);assert.deepEqual(Array.from(d.run_ids),rs.filter(rows=>rows.length===1).map(rows=>rows[0].run_id));const complete=rs.every(rows=>rows.length===1&&rows[0].full_season_complete&&rows[0].score_available!==false&&typeof rows[0].total==='number'&&rows[0].delta_vs_D_available&&typeof rows[0].delta_vs_D==='number');assert.equal(d.averageDelta,complete?rs.reduce((s,rows)=>s+rows[0].delta_vs_D,0)/2:null);assert(!d.run_ids.some(id=>id.startsWith('ext-n3-')));}assert(els.extensionHoldoutMatrix.innerHTML.includes('开发平均 ΔD'));assert(els.extensionHoldoutMatrix.innerHTML.includes('保留平均 ΔD'));const p=JSON.parse(JSON.stringify(payload));p.extension_data.rows.push({...p.extension_data.rows.find(r=>r.case_id==='D+F'),run_id:'fixture-n3-impossible-best',declared_stage:'N3',stage:'N3',delta_vs_D:99999});p.extension_data.rows=p.extension_data.rows.filter(r=>r.run_id!=='ext-n2-f-initial-dev-season');const a=fixture(p);assert.equal(a.study.extension.frozenDevelopment({case_id:'D+F'}).averageDelta,null);assert.equal(a.study.extension.frozenDevelopment({case_id:'D+F'}).available,1);});
check('extension current frozen matrix: guide order/labels, source versions, and four-card summary',()=>{const specs=payload.extension_guide.frozen_cases||[];if(!specs.length)return;assert.equal(study.extension.frozenCases().length,specs.length);let previous=-1;for(const spec of specs){const index=els.extensionHoldoutMatrix.innerHTML.indexOf('data-extension-case="'+esc(spec.case_id)+'"');assert(index>previous,spec.case_id);previous=index;assert(els.extensionHoldoutMatrix.innerHTML.includes(esc(spec.label)));const rs=['a','b','c','d'].map(c=>study.extension.frozenRow(spec.case_id,'ext-holdout-'+c)),summary=study.extension.frozenSummary(spec.case_id),complete=rs.every(r=>r?.full_season_complete&&study.extension.score(r)!==null&&study.extension.delta(r)!==null);assert.equal(summary.averageDelta,complete?rs.reduce((s,r)=>s+r.delta_vs_D,0)/4:null);assert.equal(summary.wins,complete?rs.filter(r=>r.delta_vs_D>0).length:null);for(const r of rs.filter(Boolean))assert(els.extensionHoldoutMatrix.innerHTML.includes('data-extension-score-run="'+r.run_id+'"'));const d=study.extension.frozenDevelopment(spec),devPool=[...payload.extension_data.rows,...payload.extension_data.reference_rows];for(const r of rs.filter(Boolean))for(const runId of d.run_ids){const dev=devPool.find(v=>v.run_id===runId);assert.equal(r.config_sha256,dev.config_sha256,spec.case_id+' config version');}}});
check('compact transfer overview: all 13 labels and values reuse the same development/holdout functions',()=>{assert.equal(els.extensionTransferOverview.dataset.configurationCount,study.extension.frozenCases().length);for(const spec of study.extension.frozenCases()){assert(els.extensionTransferOverview.innerHTML.includes('data-extension-transfer-case="'+spec.case_id+'"'));const row=els.extensionTransferOverview.innerHTML.split('data-extension-transfer-case="'+spec.case_id+'"')[1].split('</tr>')[0],d=study.extension.frozenDevelopment(spec),h=study.extension.frozenSummary(spec.case_id),signed=v=>v===null?'—':(v>0?'+':'')+v.toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});assert(row.includes(esc(spec.label)));assert(row.includes(signed(d.averageDelta)));assert(row.includes(signed(h.averageDelta)));assert(row.includes(h.wins===null?'—':h.wins+'/4'));}});
check('extension resize: height changes never replace tables; width changes redraw charts only and preserve checkbox state',()=>{const a=fixture(payload),observer=a.resizeObservers.find(r=>r.target===a.els['extension-holdout']);assert(observer);a.els.extensionHoldoutDelta.checked=true;const matrixWrites=a.els.extensionHoldoutMatrix.htmlWrites,summaryWrites=a.els.extensionTransferOverview.htmlWrites,chartWrites=a.els.extensionHoldoutCharts.htmlWrites;observer.callback([{contentRect:{width:625,height:1600}}]);a.flushTimers();observer.callback([{contentRect:{width:625,height:2100}}]);a.flushTimers();assert.equal(a.els.extensionHoldoutMatrix.htmlWrites,matrixWrites);assert.equal(a.els.extensionTransferOverview.htmlWrites,summaryWrites);assert.equal(a.els.extensionHoldoutCharts.htmlWrites,chartWrites);observer.callback([{contentRect:{width:392,height:2100}}]);a.flushTimers();assert.equal(a.els.extensionHoldoutMatrix.htmlWrites,matrixWrites);assert.equal(a.els.extensionTransferOverview.htmlWrites,summaryWrites);assert.equal(a.els.extensionHoldoutCharts.htmlWrites,chartWrites+1);assert.equal(a.els.extensionHoldoutDelta.checked,true);});
check('extension pending: four sealed cards display no invented zeros',()=>{const p=JSON.parse(JSON.stringify(payload));p.extension_data.rows=p.extension_data.rows.filter(r=>(r.declared_stage||r.stage)!=='N5');p.extension_guide.frozen_cases=[];const a=fixture(p);assert.equal((a.els.extensionHoldoutMatrix.innerHTML.match(/未运行（封存）/g)||[]).length,4);assert(a.els.extensionHoldoutStatus.textContent.includes('N5 未运行'));for(const c of ['a','b','c','d'])assert(a.els['extensionChartNote-ext-holdout-'+c].textContent.includes('尚未取得'));});
check('extension N5 mapping: every frozen case and four cards render totals plus same-card D differences',()=>{const p=JSON.parse(JSON.stringify(payload));p.extension_guide.frozen_cases=[{case_id:'F:fields6-rate',label:'F 6场',development_case_id:'F:fields6-rate'}];p.extension_data.rows=p.extension_data.rows.filter(r=>(r.declared_stage||r.stage)!=='N5');const template=p.extension_data.rows.find(r=>r.family==='F');for(const [i,c]of ['a','b','c','d'].entries())p.extension_data.rows.push({...template,run_id:'fixture-n5-f-'+c,case_id:'F:fields6-rate',card:'ext-holdout-'+c,declared_stage:'N5',stage:'N5',stage_group:'N5',total:i===0?0:-100*i,delta_vs_D:i===0?0:10*i,delta_vs_D_available:true,score_available:true});const a=fixture(p);assert.equal((a.els.extensionHoldoutMatrix.innerHTML.match(/data-extension-score-run=/g)||[]).length,4);assert(a.els.extensionHoldoutMatrix.innerHTML.includes('相对 D Δ'));a.els.extensionHoldoutDelta.checked=true;a.els.extensionHoldoutDelta.handlers.change();assert(a.els.extensionHoldoutMatrix.innerHTML.includes('总分'));for(const c of ['a','b','c','d'])assert(a.els['extensionChart-ext-holdout-'+c].innerHTML.includes('F 6场'));assert.equal(a.study.extension.frozenSummary('F:fields6-rate').averageDelta,15);assert.equal(a.study.extension.frozenSummary('F:fields6-rate').wins,3);assert(a.els.extensionHoldoutMatrix.innerHTML.includes('3/4'));p.extension_data.rows.pop();const missing=fixture(p);assert.equal(missing.study.extension.frozenSummary('F:fields6-rate').averageDelta,null);assert.equal(missing.study.extension.frozenSummary('F:fields6-rate').wins,null);assert(missing.els.extensionHoldoutMatrix.innerHTML.includes('3/4 已齐；暂不计算'));});
check('script execution: fixtures throw no errors and emit no console warnings/errors',()=>assert.equal(consoleMessages.length,0));
const result={method:'Node vm with minimal DOM fixture; not a real browser',cases,cases_passed:cases.length,console_messages:consoleMessages,html_sha256:crypto.createHash('sha256').update(html).digest('hex'),research_rows:payload.data.rows.length,development_configurations:18,frozen_matrix_cells:52,extension_rows:payload.extension_data.rows.length,extension_reference_rows:payload.extension_data.reference_rows.length,external_record_rows:payload.external_results?.rows?.length||0,external_scored_rows:payload.external_results?.rows?.filter(r=>typeof r.total==='number'&&r.score_available!==false).length||0,external_executed_rows:payload.external_results?.executed_runs||0,browser_verification:'Root to verify actual browser UI and console for second-study layout'};
const destination=path.join(root,'docs/v4-strategy-study.validation.json'),previous=JSON.parse(fs.readFileSync(destination,'utf8'));previous.revised_layout=result;previous.tested_output_sha256=result.html_sha256;previous.static.html_bytes=Buffer.byteLength(html);previous.browser_verification.scope='Previous R1–R5 layout only; revised overview layout awaits Root browser QA';fs.writeFileSync(destination,JSON.stringify(previous,null,2)+'\n');console.log(JSON.stringify(result,null,2));
